NAME            = 'six'
VERSION         = '0.1'
MODULE_DEPS     = 'scene sio.lite tiff nitf xml.lite'

set_options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
