DIRS = 'csm'

def options(opt):
    opt.recurse(DIRS)

def configure(conf):
    conf.recurse(DIRS)

def build(bld):
    bld.recurse(DIRS)

def distclean(context):
    context.recurse(DIRS)
