from os.path import join, isdir, exists
from os import makedirs
from waflib import Options
from build import writeConfig

USELIB_CHECK    = 'J2K'
APIS = ['external/openjpeg', 'external/jasper']
sourcepath = 'external/openjpeg/openjpeg-2.0.0'

def options(opt):
    opt.add_option('--disable-j2k', action='store_false', dest='enable_j2k', default=True,
                   help='turn off JPEG2000 support')
    opt.add_option('--j2k-layer', action='store', dest='j2k_layer',
                   choices=['openjpeg', 'jasper'], default='openjpeg', metavar='LIB',
                   help='Specify the JPEG2000 library to link with')

    opt.recurse(APIS)
    
def configure(conf):
    j2kLayer = Options.options.j2k_layer

    def j2k_callback(conf):
        if j2kLayer is 'openjpeg':
            conf.define('HAVE_OPENJPEG_H', '', quote=False)
            conf.define('J2K_MODULE_EXPORTS', '', quote=False)
        else:
            #j2kLayer is 'jasper':
            conf.define('HAVE_JASPER_H', '', quote=False)
            conf.define('J2K_MODULE_EXPORTS', '', quote=False)
    writeConfig(conf, j2k_callback, 'j2k')
        
    if Options.options.enable_j2k : 
        conf.msg('Configuring with J2K layer', Options.options.j2k_layer)
        conf.recurse(APIS)

def build(bld):
    env = bld.get_env()
    if 'HAVE_J2K' in env : 
        bld.recurse(APIS + ['shared'])
        
        if 'MAKE_OPENJPEG' in env :
            j2kLayer = 'openjpeg'
        elif 'MAKE_JASPER' in env :
            j2kLayer = 'jasper'
        else  :
            bld.fatal('Not a supported j2k type')
        
        j2kSources = ('source/Container.c',
                      'source/Component.c',
                      'source/JasPerImpl.c',
                      'source/OpenJPEGImpl.c',
                      'source/Reader.c',
                      'source/SimpleComponentImpl.c',
                      'source/SimpleContainerImpl.c',
                      'source/Writer.c')

        #build the j2k library
        lib = bld(features='c cstlib', includes='include',
                  target='j2k-c', name='j2k-c',
                  source=j2kSources,
                  export_includes='include',
                  env=env.derive(), path=bld.path,
                  use='nitf-c J2K ' + j2kLayer)
                  
        # install j2k lib
        if env['install_libs']:
           lib.install_path = env['install_libdir']
           
        # install j2k_config.h
        if env['install_headers']:
            moduleName = 'j2k'
            d = {}
            for line in env['header_builddir']:
                split = line.split('=')
                k = split[0]
                v = join(bld.bldnode.abspath(), split[1])
                d[k] = v
            
            from shutil import copyfile            
            installDir = join(bld.env['PREFIX'], 'include', 'j2k')
            destFile = join(installDir, 'j2k_config.h')
            sourceFile = join(bld.bldnode.abspath(), d[moduleName], 'j2k_config.h')            
            if not exists(installDir):
                makedirs(installDir)
            if not exists(destFile):
                copyfile(sourceFile, destFile)
            
        #j2k-only tests
        for t in ['test_j2k_header', 'test_j2k_read_tile', 'test_j2k_read_region',
                 'test_j2k_create']:
            bld.program_helper(dir='tests', source='%s.c' % t, 
                               use='j2k-c J2K ' + j2kLayer, 
                               name=t, target=t, lang='c', env=env.derive())

        #j2k/nitf tests
        for t in ['test_j2k_nitf']:
            bld.program_helper(dir='tests', source='%s.c' % t, 
                               use='nitf-c j2k-c J2K', uselib=j2kLayer, 
                               name=t, target=t, lang='c', env=env.derive())

def distclean(context) :
    context.recurse(APIS)
