NAME            = 'zip'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'io'
USELIB_CHECK    = 'MINIZIP ZIP'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
