/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgm_Metafile */

#ifndef _Included_cgm_Metafile
#define _Included_cgm_Metafile
#ifdef __cplusplus
extern "C" {
#endif
#undef cgm_Metafile_INVALID_ADDRESS
#define cgm_Metafile_INVALID_ADDRESS 0LL
/*
 * Class:     cgm_Metafile
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cgm_Metafile_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cgm_Metafile
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cgm_Metafile_getName
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Metafile
 * Method:    getVersion
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_cgm_Metafile_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Metafile
 * Method:    setVersion
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_cgm_Metafile_setVersion
  (JNIEnv *, jobject, jshort);

/*
 * Class:     cgm_Metafile
 * Method:    getDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cgm_Metafile_getDescription
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Metafile
 * Method:    setDescription
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cgm_Metafile_setDescription
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cgm_Metafile
 * Method:    getFonts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_cgm_Metafile_getFonts
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Metafile
 * Method:    setFonts
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cgm_Metafile_setFonts
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     cgm_Metafile
 * Method:    removeFont
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cgm_Metafile_removeFont
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cgm_Metafile
 * Method:    addFont
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cgm_Metafile_addFont
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cgm_Metafile
 * Method:    getPicture
 * Signature: ()Lcgm/Picture;
 */
JNIEXPORT jobject JNICALL Java_cgm_Metafile_getPicture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
