/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgm_Element_Destructor */

#ifndef _Included_cgm_Element_Destructor
#define _Included_cgm_Element_Destructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cgm_Element_Destructor
 * Method:    destructMemory
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_cgm_Element_00024Destructor_destructMemory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
