/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgm_Rectangle */

#ifndef _Included_cgm_Rectangle
#define _Included_cgm_Rectangle
#ifdef __cplusplus
extern "C" {
#endif
#undef cgm_Rectangle_INVALID_ADDRESS
#define cgm_Rectangle_INVALID_ADDRESS 0L
/*
 * Class:     cgm_Rectangle
 * Method:    getX1
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_cgm_Rectangle_getX1
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Rectangle
 * Method:    getX2
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_cgm_Rectangle_getX2
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Rectangle
 * Method:    getY1
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_cgm_Rectangle_getY1
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Rectangle
 * Method:    getY2
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_cgm_Rectangle_getY2
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Rectangle
 * Method:    setX1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_cgm_Rectangle_setX1
  (JNIEnv *, jobject, jshort);

/*
 * Class:     cgm_Rectangle
 * Method:    setX2
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_cgm_Rectangle_setX2
  (JNIEnv *, jobject, jshort);

/*
 * Class:     cgm_Rectangle
 * Method:    setY1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_cgm_Rectangle_setY1
  (JNIEnv *, jobject, jshort);

/*
 * Class:     cgm_Rectangle
 * Method:    setY2
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_cgm_Rectangle_setY2
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
