/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_ImageReader */

#ifndef _Included_nitf_ImageReader
#define _Included_nitf_ImageReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_ImageReader
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_ImageReader_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageReader
 * Method:    getInputHandle
 * Signature: ()Lnitf/IOHandle;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageReader_getInputHandle
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageReader
 * Method:    getBlockingInfo
 * Signature: ()Lnitf/BlockingInfo;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageReader_getBlockingInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageReader
 * Method:    read
 * Signature: (Lnitf/Subimage;[[B)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_ImageReader_read
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif

