/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_FileSecurity */

#ifndef _Included_nitf_FileSecurity
#define _Included_nitf_FileSecurity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_FileSecurity
 * Method:    getClassificationAuthority
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getClassificationAuthority
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getClassificationAuthorityType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getClassificationAuthorityType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getClassificationReason
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getClassificationReason
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getClassificationSystem
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getClassificationSystem
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getClassificationText
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getClassificationText
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getCodewords
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getCodewords
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getControlAndHandling
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getControlAndHandling
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getDeclassificationDate
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getDeclassificationDate
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getDeclassificationExemption
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getDeclassificationExemption
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getDeclassificationType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getDeclassificationType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getDowngrade
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getDowngrade
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getDowngradeDateTime
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getDowngradeDateTime
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getReleasingInstructions
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getReleasingInstructions
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getSecurityControlNumber
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getSecurityControlNumber
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileSecurity
 * Method:    getSecuritySourceDate
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileSecurity_getSecuritySourceDate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

