/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_SegmentReader */

#ifndef _Included_nitf_SegmentReader
#define _Included_nitf_SegmentReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_SegmentReader
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_SegmentReader_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_SegmentReader
 * Method:    read
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_SegmentReader_read
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     nitf_SegmentReader
 * Method:    seek
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_nitf_SegmentReader_seek
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     nitf_SegmentReader
 * Method:    tell
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_SegmentReader_tell
  (JNIEnv *, jobject);

/*
 * Class:     nitf_SegmentReader
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_SegmentReader_getSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

