NAME            = 'scene'
MAINTAINER      = 'adam.sylvester@mdaus.com'
MODULE_DEPS     = 'io math math.linear math.poly types'
TEST_FILTER     = 'test_scene.cpp'

options = configure = distclean = lambda p: None

def build(bld):
    modArgs = globals()
    modArgs['SIX_VERSION'] = bld.env['SIX_VERSION']
    bld.module(**modArgs)
