NAME            = 'scene'
MODULE_DEPS     = 'io math math.linear math.poly types polygon std'
TEST_FILTER     = 'test_scene.cpp'

options = configure = distclean = lambda p: None

def build(bld):
    modArgs = globals()
    modArgs['VERSION'] = bld.env['SIX_VERSION']
    bld.module(**modArgs)
