NAME            = 'plugin'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'io mem logging'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
