/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_Extensions */

#ifndef _Included_nitf_Extensions
#define _Included_nitf_Extensions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_Extensions
 * Method:    appendTRE
 * Signature: (Lnitf/TRE;)V
 */
JNIEXPORT void JNICALL Java_nitf_Extensions_appendTRE
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nitf_Extensions
 * Method:    getTREsByName
 * Signature: (Ljava/lang/String;)Ljava/lang/Iterable;
 */
JNIEXPORT jobject JNICALL Java_nitf_Extensions_getTREsByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nitf_Extensions
 * Method:    removeTREsByName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nitf_Extensions_removeTREsByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nitf_Extensions
 * Method:    exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_Extensions_exists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nitf_Extensions
 * Method:    getAll
 * Signature: ()Ljava/lang/Iterable;
 */
JNIEXPORT jobject JNICALL Java_nitf_Extensions_getAll
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Extensions
 * Method:    computeLength
 * Signature: (Lnitf/Version;)J
 */
JNIEXPORT jlong JNICALL Java_nitf_Extensions_computeLength
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif

