/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_Field */

#ifndef _Included_nitf_Field
#define _Included_nitf_Field
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     nitf_Field
 * Method:    getType
 * Signature: ()Lnitf/FieldType;
 */
JNIEXPORT jobject JNICALL Java_nitf_Field_getType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Field
 * Method:    getLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_Field_getLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Field
 * Method:    setRawData
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_Field_setRawData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     nitf_Field
 * Method:    getRawData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_nitf_Field_getRawData
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Field
 * Method:    getStringData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nitf_Field_getStringData
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Field
 * Method:    getIntData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_Field_getIntData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

