/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_FileHeader */

#ifndef _Included_nitf_FileHeader
#define _Included_nitf_FileHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_FileHeader
 * Method:    getBackgroundColor
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getBackgroundColor
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getClassification
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getClassification
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getComplianceLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getComplianceLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getEncrypted
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getEncrypted
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getExtendedHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getExtendedHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getExtendedHeaderOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getExtendedHeaderOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileDateTime
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileDateTime
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileHeader
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileHeader
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileTitle
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileTitle
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileVersion
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileVersion
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getMessageCopyNum
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getMessageCopyNum
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getMessageNumCopies
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getMessageNumCopies
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumDataExtensions
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumDataExtensions
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumGraphics
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumGraphics
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumImages
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumImages
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumLabels
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumLabels
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumReservedExtensions
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumReservedExtensions
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumTexts
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumTexts
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getOriginatorName
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getOriginatorName
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getOriginatorPhone
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getOriginatorPhone
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getOriginStationID
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getOriginStationID
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getSecurityGroup
 * Signature: ()Lnitf/FileSecurity;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getSecurityGroup
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getSystemType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getSystemType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getUserDefinedHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getUserDefinedHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getUserDefinedOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getUserDefinedOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getImageInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getImageInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getGraphicInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getGraphicInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getLabelInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getLabelInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getTextInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getTextInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getDataExtensionInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getDataExtensionInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getReservedExtensionInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getReservedExtensionInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getUserDefinedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getUserDefinedSection
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getExtendedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getExtendedSection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

