/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_Record */

#ifndef _Included_nitf_Record
#define _Included_nitf_Record
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_Record
 * Method:    construct
 * Signature: (Lnitf/Version;)V
 */
JNIEXPORT void JNICALL Java_nitf_Record_construct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nitf_Record
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_Record_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Record
 * Method:    makeClone
 * Signature: ()Lnitf/Cloneable;
 */
JNIEXPORT jobject JNICALL Java_nitf_Record_makeClone
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Record
 * Method:    getHeader
 * Signature: ()Lnitf/FileHeader;
 */
JNIEXPORT jobject JNICALL Java_nitf_Record_getHeader
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Record
 * Method:    getImages
 * Signature: ()[Lnitf/ImageSegment;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_Record_getImages
  (JNIEnv *, jobject);

/*
* Class:     nitf_Record
* Method:    getGraphics
* Signature: ()[Lnitf/GraphicSegment;
*/
JNIEXPORT jobjectArray JNICALL Java_nitf_Record_getGraphics
 (JNIEnv *, jobject);

/*
* Class:     nitf_Record
* Method:    getLabels
* Signature: ()[Lnitf/LabelSegment;
*/
JNIEXPORT jobjectArray JNICALL Java_nitf_Record_getLabels
 (JNIEnv *, jobject);

/*
* Class:     nitf_Record
* Method:    getTexts
* Signature: ()[Lnitf/TextSegment;
*/
JNIEXPORT jobjectArray JNICALL Java_nitf_Record_getTexts
 (JNIEnv *, jobject);

/*
* Class:     nitf_Record
* Method:    getDataExtensions
* Signature: ()[Lnitf/DESegment;
*/
JNIEXPORT jobjectArray JNICALL Java_nitf_Record_getDataExtensions
 (JNIEnv *, jobject);

/*
* Class:     nitf_Record
* Method:    getReservedExtensions
* Signature: ()[Lnitf/RESegment;
*/
JNIEXPORT jobjectArray JNICALL Java_nitf_Record_getReservedExtensions
 (JNIEnv *, jobject);

/*
 * Class:     nitf_Record
 * Method:    newImageSegment
 * Signature: ()Lnitf/ImageSegment;
 */
JNIEXPORT jobject JNICALL Java_nitf_Record_newImageSegment
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Record
 * Method:    newGraphicSegment
 * Signature: ()Lnitf/GraphicSegment;
 */
JNIEXPORT jobject JNICALL Java_nitf_Record_newGraphicSegment
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Record
 * Method:    newTextSegment
 * Signature: ()Lnitf/TextSegment;
 */
JNIEXPORT jobject JNICALL Java_nitf_Record_newTextSegment
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Record
 * Method:    removeImageSegment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_Record_removeImageSegment
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_Record
 * Method:    removeGraphicSegment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_Record_removeGraphicSegment
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_Record
 * Method:    removeLabelSegment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_Record_removeLabelSegment
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_Record
 * Method:    removeTextSegment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_Record_removeTextSegment
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_Record
 * Method:    removeDataExtensionSegment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_Record_removeDataExtensionSegment
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_Record
 * Method:    removeReservedExtensionSegment
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_Record_removeReservedExtensionSegment
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_Record
 * Method:    getVersion
 * Signature: ()Lnitf/NITFVersion;
 */
JNIEXPORT jobject JNICALL Java_nitf_Record_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

