/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_TREDescription */

#ifndef _Included_nitf_TREDescription
#define _Included_nitf_TREDescription
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     nitf_TREDescription
 * Method:    construct
 * Signature: (Lnitf/TREDescriptionDataType;ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nitf_TREDescription_construct
  (JNIEnv *, jobject, jobject, jint, jstring, jstring);

/*
 * Class:     nitf_TREDescription
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_TREDescription_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TREDescription
 * Method:    getDataType
 * Signature: ()Lnitf/TREDescriptionDataType;
 */
JNIEXPORT jobject JNICALL Java_nitf_TREDescription_getDataType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TREDescription
 * Method:    getDataCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_TREDescription_getDataCount
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TREDescription
 * Method:    getLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nitf_TREDescription_getLabel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TREDescription
 * Method:    getTag
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nitf_TREDescription_getTag
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

