/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_TRE */

#ifndef _Included_nitf_TRE
#define _Included_nitf_TRE
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_TRE_DEFAULT_LENGTH
#define nitf_TRE_DEFAULT_LENGTH 0L
/*
 * Class:     nitf_TRE
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_TRE_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_nitf_TRE_construct
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     nitf_TRE
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_TRE_getLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    setLength
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_TRE_setLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_TRE
 * Method:    getTag
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nitf_TRE_getTag
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_TRE_exists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nitf_TRE
 * Method:    find
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_nitf_TRE_find
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nitf_TRE
 * Method:    getField
 * Signature: (Ljava/lang/String;)Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TRE_getField
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nitf_TRE
 * Method:    setField
 * Signature: (Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_TRE_setField
  (JNIEnv *, jobject, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
