/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_DESubheader */

#ifndef _Included_nitf_DESubheader
#define _Included_nitf_DESubheader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_DESubheader
 * Method:    getFilePartType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getFilePartType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getTypeID
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getTypeID
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getSecurityClass
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getSecurityClass
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getSecurityGroup
 * Signature: ()Lnitf/FileSecurity;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getSecurityGroup
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getVersion
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getOverflowedHeaderType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getOverflowedHeaderType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getDataItemOverflowed
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getDataItemOverflowed
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getSubheaderFieldsLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getSubheaderFieldsLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getSubheaderFields
 * Signature: ()Lnitf/TRE;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getSubheaderFields
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    getDataLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_DESubheader_getDataLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_DESubheader
 * Method:    setDataLength
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nitf_DESubheader_setDataLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     nitf_DESubheader
 * Method:    getUserDefinedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_DESubheader_getUserDefinedSection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

