/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_TRE */

#ifndef _Included_nitf_TRE
#define _Included_nitf_TRE
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_TRE_DEFAULT_LENGTH
#define nitf_TRE_DEFAULT_LENGTH 0L
/*
 * Class:     nitf_TRE
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_TRE_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    construct
 * Signature: (Ljava/lang/String;I[Lnitf/TREDescription;)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_TRE_construct
  (JNIEnv *, jobject, jstring, jint, jobjectArray);

/*
 * Class:     nitf_TRE
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_TRE_getLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    setLength
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_TRE_setLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_TRE
 * Method:    computeLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_TRE_computeLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    getTREDescription
 * Signature: ()[Lnitf/TREDescription;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_TRE_getTREDescription
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    getTag
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nitf_TRE_getTag
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_TRE_exists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nitf_TRE
 * Method:    getField
 * Signature: (Ljava/lang/String;)Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TRE_getField
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nitf_TRE
 * Method:    setField
 * Signature: (Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_TRE_setField
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     nitf_TRE
 * Method:    isSane
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_TRE_isSane
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE
 * Method:    getFields
 * Signature: ()[Lnitf/TRE/TREField;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_TRE_getFields
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

