import os
from os.path import join
import Scripting, Options
from Build import BuildContext

VERSION = '0.2'
APPNAME = 'Sensor Independent XML'
srcdir  = '.'
blddir  = 'target'

def set_options(opt):
    opt.tool_options('build swig pythontool',
                     tooldir=join(opt.curdir, 'build'))
    opt.sub_options('drivers c++ python')

def configure(conf):
    conf.check_tool('build swig pythontool',
                    tooldir=join(conf.curdir, 'build'))
    conf.sub_config('drivers c++ python')

def build(bld):
    bld.add_subdirs('drivers drivers/nitf c++ python')

def distclean(context):
    context.recurse('drivers c++ python')
    Scripting.distclean(context)

def init(context):
    """
    Override the lockfile - which allows you to build on multiple platforms
    from the same sandbox without needing to re-configure every time you swap
    between platforms.
    
    In other words, configure once per platform, then you can build for each
    """
    from build import getPlatform
    platform = getPlatform()
    Options.lockfile = '.lock-%s' % platform