import os
from os.path import join
import Scripting, Options
from Build import BuildContext

VERSION = '1.0'
APPNAME = 'Sensor Independent XML'
srcdir  = '.'
blddir  = 'target'

DIRS = 'drivers drivers/nrt drivers/nitf drivers/j2k c++ python'

def set_options(opt):
    opt.tool_options('build swig pythontool',
                     tooldir=join(opt.curdir, 'build'))
    opt.sub_options(DIRS)

def configure(conf):
    conf.check_tool('build swig pythontool',
                    tooldir=join(conf.curdir, 'build'))
    conf.sub_config(DIRS)

def build(bld):
    bld.add_subdirs(DIRS)

def distclean(context):
    context.recurse(DIRS)
    Scripting.distclean(context)
