import os

VERSION = '2.9'

def options(opt):
    opt.recurse()

def configure(conf):
    conf.env['VERSION'] = VERSION
    conf.define('NITF_DEFAULT_PLUGIN_PATH',
                os.path.join(os.path.abspath(conf.options.prefix),
                             'share', 'nitf', 'plugins'))
    conf.recurse()

def build(bld):
    if bld.env['LIB_TYPE'] == 'shlib':
        bld.recurse('drivers c')
    else:
        bld.recurse()

def distclean(context):
    context.recurse()
