#!/usr/bin/env python

import os, sys, subprocess

coda_oss = 'coda-oss'
path_to_waf = os.path.join(os.path.dirname(__file__), 'externals', coda_oss, 'build', 'waf')

cmd = [sys.executable, path_to_waf] + sys.argv[1:]
try:
    sys.exit(subprocess.call(cmd))
except KeyboardInterrupt:
    sys.exit(1)
