#!/usr/bin/env python

import os, sys
path_to_waf = os.path.join(os.path.dirname(__file__), 'build', 'waf')
cmd = '"' + sys.executable + '" ' + path_to_waf + ' ' + ' '.join(sys.argv[1:])
sys.exit(os.system(cmd))
