distclean = options = configure = lambda p: None

def build(bld):
  bld.swigModule(name = 'cphd03',
                 use = 'cphd03-c++ cphd-c++ types-python mem-python six.sicd-python six-python sys-python',
                 package = 'pysix')
