import os, shutil
from waflib import Options
from build import unzipper

MAINTAINER         = 'adam.sylvester@mdaus.com'
VERSION            = '1.0'
LANG               = 'c'
NAME               = 'LibjpegDecompress'
LIBNAME            = 'LibjpegDecompress'
REMOVEPLUGINPREFIX = True
USE                = 'nitf-c'
USELIB_CHECK       = 'JPEG'
PLUGIN             = 'nitf'
DEFINES            = 'NITF_MODULE_EXPORTS'

configure = options = distclean = lambda p: None

def build(bld):
    if 'HAVE_JPEG' in bld.get_env() :
        bld.plugin(**globals())
