NAME            = 'samples'
VERSION         = '0.1'
MODULE_DEPS     = 'scene tiff nitf xml.lite six six.sicd six.sidd cli sio.lite fft'
USELIB          = 'SIX_SAMPLES'

options = configure = distclean = lambda p: None

SAMPLES = 'round_trip_six test_extract_xml test_create_sicd test_dump_images ' \
          'test_create_sidd test_create_sidd_from_mem test_parse_xml'

def build(bld):
    for sample in SAMPLES.split():
        bld.program_helper(uselib=USELIB,
                    module_deps=MODULE_DEPS,
                    source='%s.cpp' % sample,
                    name=sample)
