configure = options = distclean = lambda x: None

def build(bld):
    variant = bld.env['VARIANT']
    env = bld.env_of_name(variant)
    
    if env['HAVE_JNI_H']:
        lib = bld.new_task_gen(features='c cshlib', includes='src/jni/include',
                               target='cgm.jni-c', env=env.copy(),
                               uselib='JAVA', use='cgm-c'.split())
        lib.source = bld.path.ant_glob('src/jni/source/*.c*')
