NAME            = 'mem'
VERSION         = '1.0'
MODULE_DEPS     = 'sys gsl coda_oss std'
TEST_DEPS       = 'cli std'
UNITTEST_DEPS       = 'std'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
