/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_TRE_TREIterator */

#ifndef _Included_nitf_TRE_TREIterator
#define _Included_nitf_TRE_TREIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_TRE_TREIterator
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_TRE_00024TREIterator_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE_TREIterator
 * Method:    next
 * Signature: ()Lnitf/TRE/FieldPair;
 */
JNIEXPORT jobject JNICALL Java_nitf_TRE_00024TREIterator_next
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE_TREIterator
 * Method:    construct
 * Signature: (Lnitf/TRE;)V
 */
JNIEXPORT void JNICALL Java_nitf_TRE_00024TREIterator_construct
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
