/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_LabelSubheader */

#ifndef _Included_nitf_LabelSubheader
#define _Included_nitf_LabelSubheader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_LabelSubheader
 * Method:    getFilePartType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getFilePartType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getLabelID
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getLabelID
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getSecurityClass
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getSecurityClass
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getSecurityGroup
 * Signature: ()Lnitf/FileSecurity;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getSecurityGroup
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getEncrypted
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getEncrypted
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getFontStyle
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getFontStyle
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getCellWidth
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getCellWidth
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getCellHeight
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getCellHeight
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getDisplayLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getDisplayLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getAttachmentLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getAttachmentLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getLocationRow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getLocationRow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getLocationColumn
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getLocationColumn
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getTextColor
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getTextColor
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getBackgroundColor
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getBackgroundColor
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getExtendedHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getExtendedHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getExtendedHeaderOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getExtendedHeaderOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LabelSubheader
 * Method:    getExtendedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_LabelSubheader_getExtendedSection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

