/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_SegmentWriter */

#ifndef _Included_nitf_SegmentWriter
#define _Included_nitf_SegmentWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_SegmentWriter
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_SegmentWriter_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_SegmentWriter
 * Method:    getOutputHandle
 * Signature: ()Lnitf/IOHandle;
 */
JNIEXPORT jobject JNICALL Java_nitf_SegmentWriter_getOutputHandle
  (JNIEnv *, jobject);

/*
 * Class:     nitf_SegmentWriter
 * Method:    getSegmentSource
 * Signature: ()Lnitf/SegmentSource;
 */
JNIEXPORT jobject JNICALL Java_nitf_SegmentWriter_getSegmentSource
  (JNIEnv *, jobject);

/*
 * Class:     nitf_SegmentWriter
 * Method:    attachSource
 * Signature: (Lnitf/SegmentSource;)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_SegmentWriter_attachSource
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif

