/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_ImageSubheader */

#ifndef _Included_nitf_ImageSubheader
#define _Included_nitf_ImageSubheader
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_ImageSubheader_INVALID_ADDRESS
#define nitf_ImageSubheader_INVALID_ADDRESS 0L
/*
 * Class:     nitf_ImageSubheader
 * Method:    getActualBitsPerPixel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getActualBitsPerPixel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getBandInfo
 * Signature: ()[Lnitf/BandInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_ImageSubheader_getBandInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getCompressionRate
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getCompressionRate
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getCornerCoordinates
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getCornerCoordinates
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getEncrypted
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getEncrypted
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getExtendedHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getExtendedHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getExtendedHeaderOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getExtendedHeaderOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getFilePartType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getFilePartType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageAttachmentLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageAttachmentLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageCategory
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageCategory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageComments
 * Signature: ()[Lnitf/Field;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_ImageSubheader_getImageComments
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageCompression
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageCompression
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageCoordinateSystem
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageCoordinateSystem
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageDateAndTime
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageDateAndTime
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageDisplayLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageDisplayLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageId
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageId
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageLocation
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageLocation
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageMagnification
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageMagnification
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageMode
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageMode
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageRepresentation
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageRepresentation
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageSecurityClass
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageSecurityClass
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageSource
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageSource
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageSyncCode
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageSyncCode
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getImageTitle
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getImageTitle
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumBitsPerPixel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumBitsPerPixel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumBlocksPerCol
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumBlocksPerCol
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumBlocksPerRow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumBlocksPerRow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumCols
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumCols
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumImageBands
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumImageBands
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumImageComments
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumImageComments
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumMultispectralImageBands
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumMultispectralImageBands
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumPixelsPerHorizBlock
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumPixelsPerHorizBlock
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumPixelsPerVertBlock
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumPixelsPerVertBlock
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getNumRows
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getNumRows
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getPixelJustification
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getPixelJustification
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getPixelValueType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getPixelValueType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getSecurityGroup
 * Signature: ()Lnitf/FileSecurity;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getSecurityGroup
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getTargetId
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getTargetId
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getUserDefinedImageDataLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getUserDefinedImageDataLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getUserDefinedOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getUserDefinedOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getUserDefinedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getUserDefinedSection
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getExtendedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSubheader_getExtendedSection
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    insertImageComment
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_nitf_ImageSubheader_insertImageComment
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     nitf_ImageSubheader
 * Method:    removeImageComment
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_ImageSubheader_removeImageComment
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_ImageSubheader
 * Method:    getBandCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_ImageSubheader_getBandCount
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSubheader
 * Method:    createBands
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_ImageSubheader_createBands
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_ImageSubheader
 * Method:    removeBand
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_ImageSubheader_removeBand
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
