/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_ImageSource */

#ifndef _Included_nitf_ImageSource
#define _Included_nitf_ImageSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_ImageSource
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_ImageSource_construct
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSource
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_ImageSource_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSource
 * Method:    getBandSources
 * Signature: ()[Lnitf/BandSource;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_ImageSource_getBandSources
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSource
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_ImageSource_getSize
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSource
 * Method:    addBand
 * Signature: (Lnitf/BandSource;)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_ImageSource_addBand
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nitf_ImageSource
 * Method:    getBand
 * Signature: (I)Lnitf/BandSource;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSource_getBand
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif

