/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_GraphicSubheader */

#ifndef _Included_nitf_GraphicSubheader
#define _Included_nitf_GraphicSubheader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_GraphicSubheader
 * Method:    getFilePartType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getFilePartType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getGraphicID
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getGraphicID
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getName
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getName
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getSecurityClass
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getSecurityClass
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getSecurityGroup
 * Signature: ()Lnitf/FileSecurity;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getSecurityGroup
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getEncrypted
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getEncrypted
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getStype
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getStype
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getRes1
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getRes1
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getDisplayLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getDisplayLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getAttachmentLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getAttachmentLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getLocation
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getLocation
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getBound1Loc
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getBound1Loc
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getColor
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getColor
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getBound2Loc
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getBound2Loc
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getRes2
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getRes2
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getExtendedHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getExtendedHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getExtendedHeaderOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getExtendedHeaderOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_GraphicSubheader
 * Method:    getExtendedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_GraphicSubheader_getExtendedSection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

