/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_FileSource */

#ifndef _Included_nitf_FileSource
#define _Included_nitf_FileSource
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_FileSource_INVALID_ADDRESS
#define nitf_FileSource_INVALID_ADDRESS 0L
/*
 * Class:     nitf_FileSource
 * Method:    construct
 * Signature: (Lnitf/IOHandle;JII)V
 */
JNIEXPORT void JNICALL Java_nitf_FileSource_construct
  (JNIEnv *, jobject, jobject, jlong, jint, jint);

/*
 * Class:     nitf_FileSource
 * Method:    read
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_nitf_FileSource_read
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
