/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_FieldWarning */

#ifndef _Included_nitf_FieldWarning
#define _Included_nitf_FieldWarning
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     nitf_FieldWarning
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_FieldWarning_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FieldWarning
 * Method:    getFieldName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nitf_FieldWarning_getFieldName
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FieldWarning
 * Method:    getField
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FieldWarning_getField
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FieldWarning
 * Method:    getWarning
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nitf_FieldWarning_getWarning
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FieldWarning
 * Method:    getFileOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_FieldWarning_getFileOffset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

