/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_WriteHandler */

#ifndef _Included_nitf_WriteHandler
#define _Included_nitf_WriteHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_WriteHandler_INVALID_ADDRESS
#define nitf_WriteHandler_INVALID_ADDRESS 0LL
/*
 * Class:     nitf_WriteHandler
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_WriteHandler_construct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
