/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_TextSubheader */

#ifndef _Included_nitf_TextSubheader
#define _Included_nitf_TextSubheader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_TextSubheader
 * Method:    getFilePartType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getFilePartType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getTextID
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getTextID
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getAttachmentLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getAttachmentLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getDateTime
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getDateTime
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getTitle
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getTitle
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getSecurityClass
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getSecurityClass
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getSecurityGroup
 * Signature: ()Lnitf/FileSecurity;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getSecurityGroup
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getEncrypted
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getEncrypted
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getFormat
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getFormat
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getExtendedHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getExtendedHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getExtendedHeaderOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getExtendedHeaderOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TextSubheader
 * Method:    getExtendedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_TextSubheader_getExtendedSection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

