/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_MaxDownSampler */

#ifndef _Included_nitf_MaxDownSampler
#define _Included_nitf_MaxDownSampler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_MaxDownSampler
 * Method:    construct
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_nitf_MaxDownSampler_construct
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    apply
 * Signature: ([[B[[BIIIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_MaxDownSampler_apply
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    getRowSkip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_MaxDownSampler_getRowSkip
  (JNIEnv *, jobject);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    getColSkip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_MaxDownSampler_getColSkip
  (JNIEnv *, jobject);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    getMinSupportedBands
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_MaxDownSampler_getMinSupportedBands
  (JNIEnv *, jobject);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    getMaxSupportedBands
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_MaxDownSampler_getMaxSupportedBands
  (JNIEnv *, jobject);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    isMultiBand
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_MaxDownSampler_isMultiBand
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

