/* =========================================================================
 * This file is part of NITRO
 * =========================================================================
 * 
 * (C) Copyright 2004 - 2008, General Dynamics - Advanced Information Systems
 *
 * NITRO is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this program; if not, If not, 
 * see <http://www.gnu.org/licenses/>.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <import/nitf.h>
/* Header for class nitf_BlockingInfo */

#ifndef _Included_nitf_BlockingInfo
#define _Included_nitf_BlockingInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_BlockingInfo
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_BlockingInfo_destructMemory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BlockingInfo
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_BlockingInfo_construct
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BlockingInfo
 * Method:    getNumBlocksPerRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_BlockingInfo_getNumBlocksPerRow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BlockingInfo
 * Method:    setNumBlocksPerRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_BlockingInfo_setNumBlocksPerRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_BlockingInfo
 * Method:    getNumBlocksPerCol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_BlockingInfo_getNumBlocksPerCol
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BlockingInfo
 * Method:    setNumBlocksPerCol
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_BlockingInfo_setNumBlocksPerCol
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_BlockingInfo
 * Method:    getNumRowsPerBlock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_BlockingInfo_getNumRowsPerBlock
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BlockingInfo
 * Method:    setNumRowsPerBlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_BlockingInfo_setNumRowsPerBlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_BlockingInfo
 * Method:    getNumColsPerBlock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_BlockingInfo_getNumColsPerBlock
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BlockingInfo
 * Method:    setNumColsPerBlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_BlockingInfo_setNumColsPerBlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     nitf_BlockingInfo
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_BlockingInfo_getLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BlockingInfo
 * Method:    setLength
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nitf_BlockingInfo_setLength
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif

