/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_ImageSegment */

#ifndef _Included_nitf_ImageSegment
#define _Included_nitf_ImageSegment
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_ImageSegment_INVALID_ADDRESS
#define nitf_ImageSegment_INVALID_ADDRESS 0L
/*
 * Class:     nitf_ImageSegment
 * Method:    getSubheader
 * Signature: ()Lnitf/ImageSubheader;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageSegment_getSubheader
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSegment
 * Method:    getImageOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_ImageSegment_getImageOffset
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageSegment
 * Method:    getImageEnd
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_ImageSegment_getImageEnd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
