/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_BandInfo */

#ifndef _Included_nitf_BandInfo
#define _Included_nitf_BandInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_BandInfo_INVALID_ADDRESS
#define nitf_BandInfo_INVALID_ADDRESS 0L
/*
 * Class:     nitf_BandInfo
 * Method:    getBandEntriesPerLUT
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_BandInfo_getBandEntriesPerLUT
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BandInfo
 * Method:    getImageFilterCode
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_BandInfo_getImageFilterCode
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BandInfo
 * Method:    getImageFilterCondition
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_BandInfo_getImageFilterCondition
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BandInfo
 * Method:    getNumLUTs
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_BandInfo_getNumLUTs
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BandInfo
 * Method:    getRepresentation
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_BandInfo_getRepresentation
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BandInfo
 * Method:    getSubcategory
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_BandInfo_getSubcategory
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BandInfo
 * Method:    getLookupTable
 * Signature: ()Lnitf/LookupTable;
 */
JNIEXPORT jobject JNICALL Java_nitf_BandInfo_getLookupTable
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BandInfo
 * Method:    setLookupTable
 * Signature: (Lnitf/LookupTable;)V
 */
JNIEXPORT void JNICALL Java_nitf_BandInfo_setLookupTable
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
