/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_TRE_TREIterator */

#ifndef _Included_nitf_TRE_TREIterator
#define _Included_nitf_TRE_TREIterator
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_TRE_TREIterator_INVALID_ADDRESS
#define nitf_TRE_TREIterator_INVALID_ADDRESS 0LL
/*
 * Class:     nitf_TRE_TREIterator
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_TRE_00024TREIterator_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE_TREIterator
 * Method:    next
 * Signature: ()Lnitf/TRE/FieldPair;
 */
JNIEXPORT jobject JNICALL Java_nitf_TRE_00024TREIterator_next
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE_TREIterator
 * Method:    getFieldDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nitf_TRE_00024TREIterator_getFieldDescription
  (JNIEnv *, jobject);

/*
 * Class:     nitf_TRE_TREIterator
 * Method:    construct
 * Signature: (Lnitf/TRE;)V
 */
JNIEXPORT void JNICALL Java_nitf_TRE_00024TREIterator_construct
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
