/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_BandSource */

#ifndef _Included_nitf_BandSource
#define _Included_nitf_BandSource
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_BandSource_INVALID_ADDRESS
#define nitf_BandSource_INVALID_ADDRESS 0L
/*
 * Class:     nitf_BandSource
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_BandSource_construct
  (JNIEnv *, jobject);

/*
 * Class:     nitf_BandSource
 * Method:    destructMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_BandSource_destructMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
