NAME            = 'math.poly'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '0.2'
MODULE_DEPS     = 'sys math.linear'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
