from build import writeConfig
NAME            = 'math'
VERSION         = '0.1'
USELIB          = 'MATH'
MODULE_DEPS     = 'except str sys types coda_oss'
TEST_DEPS       = 'std'

options = distclean = lambda p: None


def configure(conf):
    def math_callback(conf):
        print("math_callback");

    writeConfig(conf, math_callback, NAME)

def build(bld):
    bld.module(**globals())
