NAME            = 'str'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'except'
UNITTEST_DEPS   = 'sys'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
