NAME            = 'six.sicd'
MAINTAINER      = 'adam.sylvester@mdaus.com'
MODULE_DEPS     = 'scene nitf xml.lite six mem'
TEST_DEPS       = 'cli'
UNITTEST_DEPS   = 'cli sio.lite'

import os

options = configure = distclean = lambda p: None

def build(bld):
    modArgs = globals()
    modArgs['VERSION'] = bld.env['SIX_VERSION']
    bld.module(**modArgs)

    # install the schemas
    lib = bld.get_tgen_by_name('six.sicd-c++')
    lib.targets_to_add.append(bld(features='install_tgt', pattern='**/*',
                                  dir=bld.path.make_node('conf/schema'),
                                  install_path='${PREFIX}/conf/schema/six/'))

    if ('PYTHON' in bld.env and bld.env['PYTHON'] and
            bld.is_defined('HAVE_PYTHON_H')):
        bld(features='install_tgt', pattern='**/*',
            dir=bld.path.make_node('conf/schema'),
            name='python_sicd_schemas',
            install_path=os.path.join(
                bld.env['install_pydir'], 'pysix', 'schemas'))
