import sys
import os

def options(opt):
    opt.recurse()

def configure(conf):
    conf.env['SIX_VERSION'] = '2.2.9-alpha'

    # This allows us to build XML_DATA_CONTENT statically so that users don't
    # have to set NITF_PLUGIN_PATH
    conf.env['enable_static_tres'] = True

    conf.recurse()

def build(bld):
    bld.recurse()

def distclean(context):
    context.recurse()
