import sys
import os

def options(opt):
    opt.recurse()

def configure(conf):
    conf.env['SIX_VERSION'] = '3.0.0'

    # This allows us to build XML_DATA_CONTENT statically so that users don't
    # have to set NITF_PLUGIN_PATH
    conf.env['enable_static_tres'] = True

    conf.define('DEFAULT_SCHEMA_PATH',
                os.path.join(os.path.abspath(conf.options.prefix),
                             'conf', 'schema', 'six'))

    conf.recurse()

def build(bld):
    bld.recurse()

def distclean(context):
    context.recurse()
