NAME            = 'hdf5.lite'
VERSION         = '1.0'
MODULE_DEPS     = 'highfive hdf5 hdf5cpp except types io coda_oss'
USELIB_LOCAL    = 'hdf5-c hdf5cpp-c'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
