NAME            = 'hdf5.lite'
VERSION         = '1.0'
MODULE_DEPS     = 'hdf5 hdf5cpp str except io logging sys coda_oss config gsl'
USELIB_LOCAL    = 'hdf5-c hdf5cpp-c'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
