/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cgm_Picture */

#ifndef _Included_cgm_Picture
#define _Included_cgm_Picture
#ifdef __cplusplus
extern "C" {
#endif
#undef cgm_Picture_INVALID_ADDRESS
#define cgm_Picture_INVALID_ADDRESS 0L
/*
 * Class:     cgm_Picture
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cgm_Picture_getName
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Picture
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cgm_Picture_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cgm_Picture
 * Method:    getVDCExtent
 * Signature: ()Lcgm/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_cgm_Picture_getVDCExtent
  (JNIEnv *, jobject);

/*
 * Class:     cgm_Picture
 * Method:    getPictureBody
 * Signature: ()Lcgm/PictureBody;
 */
JNIEXPORT jobject JNICALL Java_cgm_Picture_getPictureBody
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
