
import os
from os.path import join, basename
from waflib import Utils

distclean = options = configure = lambda p: None

def build(bld):
    bld.swigModule(name = 'mt',
                   use = 'sys-c++ except-python mem-python types-python ' \
                         'mt-c++' ,
                   package = 'coda')

