import os

options = configure = distclean = lambda p: None

def build(bld):
    bld(features='subst',
        name='six_setup',
        source='setup.py.in',
        target='setup.py',
        SIX_VERSION=bld.env['SIX_VERSION'],
        LIBDIR=bld.env['install_libdir'])
    bld.env['SETUP_PY_DIR'] = os.path.join(bld.getBuildDir(), 'six', 'conf')
