import os

options = distclean = lambda p: None

def configure(conf):
    if 'WHEEL_MAP' not in conf.env:
        conf.env['WHEEL_MAP'] = {}
    conf.env['WHEEL_MAP']['pysix'] = conf.getBuildDir()

def build(bld):
    bld(features='subst',
        name='six_setup',
        source='setup.py.in',
        target='setup.py',
        SIX_VERSION=bld.env['SIX_VERSION'],
        LIBDIR=bld.env['install_libdir'])
