from waflib import Options
from javatool import java_module

NAME            = 'nitf.imagej'
MAINTAINER      = 'asylvest@users.sourceforge.net'
VERSION         = '2.7'
MODULE_DEPS     = 'nitf nitf.imageio'
CLASSPATH       = 'ij-1.42.jar'
COMPAT          = '1.5'

configure = options = distclean = lambda x: None

def build(bld):
    java_module(bld, **globals())	
