NAME            = 'sio.lite'
MAINTAINER      = 'dan.pressel@gd-ais.com thomas.zellman@gd-ais.com'
VERSION         = '1.0'
MODULE_DEPS     = 'io types'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
