NAME            = 'six.sidd'
VERSION         = '0.1'
MODULE_DEPS     = 'scene tiff nitf xml.lite six'

set_options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
