NAME            = 'six.sidd'
MAINTAINER      = 'asylvest@users.sourceforge.net'
VERSION         = '0.1'
MODULE_DEPS     = 'scene tiff nitf xml.lite six mem'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())

    # install the schemas
    lib = bld.get_tgen_by_name('six.sidd-c++')
    lib.targets_to_add.append(bld(features='install_tgt', pattern='**/*',
                                  dir=bld.path.make_node('conf/schema'),
                                  install_path='${PREFIX}/conf/schema/six/'))