import os
from waflib import Options, Build
from waflib.Errors import ConfigurationError

def options(opt):
    opt.recurse('nitf cgm')

def configure(conf):
    conf.recurse('nitf cgm')

def build(bld):
    bld.recurse('nitf cgm')

def distclean(context):
    pass
