import os
import Options, Build
from Configure import ConfigurationError

set_options = configure = distclean = lambda x: None

def build(bld):
    variant = bld.env['VARIANT'] or 'default'
    env = bld.env_of_name(variant)
    
    if 'JAVA' in env:
        bld.add_subdirs('nitf cgm')

def distclean(context):
    pass
