BLD_DIRS = 'pcre xml'

def options(opt):
    opt.recurse(BLD_DIRS)

def configure(conf):
    conf.recurse(BLD_DIRS)

def build(bld):
    bld.recurse(BLD_DIRS)

def distclean(ctx):
    ctx.recurse(BLD_DIRS)
