import os, subprocess
from waflib import Options
from os.path import splitext, dirname, join

MAINTAINER         = 'adam.sylvester@gd-ais.com'
VERSION            = '1.0'
LANG               = 'c'
USE                = 'nitf-c'
PLUGIN             = 'nitf'
REMOVEPLUGINPREFIX = True
DEFINES            = ['NITF_MODULE_EXPORTS']

configure = options = distclean = lambda p: None

def build(bld):
    variant = bld.env['VARIANT'] or 'default'
    env = bld.all_envs[variant]
    
    pluginList = []
    plugins = bld.path.ant_glob('*.c')

    for p in plugins:
        filename = str(p)

        kw = globals()
        pluginName = splitext(filename)[0]
        kw['NAME'] = pluginName
        kw['LIBNAME'] = pluginName
        kw['SOURCE'] = filename

        bld.plugin(**kw)
        pluginList.append(pluginName)

    bld(features='add_targets', target='nitro-plugins',
        targets_to_add=pluginList)
