/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_LookupTable */

#ifndef _Included_nitf_LookupTable
#define _Included_nitf_LookupTable
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_LookupTable_INVALID_ADDRESS
#define nitf_LookupTable_INVALID_ADDRESS 0LL
/*
 * Class:     nitf_LookupTable
 * Method:    construct
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_nitf_LookupTable_construct
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     nitf_LookupTable
 * Method:    getNumTables
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_LookupTable_getNumTables
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LookupTable
 * Method:    getNumEntries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_LookupTable_getNumEntries
  (JNIEnv *, jobject);

/*
 * Class:     nitf_LookupTable
 * Method:    getData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_nitf_LookupTable_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
