/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_RESegment */

#ifndef _Included_nitf_RESegment
#define _Included_nitf_RESegment
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_RESegment_INVALID_ADDRESS
#define nitf_RESegment_INVALID_ADDRESS 0L
/*
 * Class:     nitf_RESegment
 * Method:    getSubheader
 * Signature: ()Lnitf/RESubheader;
 */
JNIEXPORT jobject JNICALL Java_nitf_RESegment_getSubheader
  (JNIEnv *, jobject);

/*
 * Class:     nitf_RESegment
 * Method:    getOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_RESegment_getOffset
  (JNIEnv *, jobject);

/*
 * Class:     nitf_RESegment
 * Method:    getEnd
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nitf_RESegment_getEnd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
