/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_DownSampler */

#ifndef _Included_nitf_DownSampler
#define _Included_nitf_DownSampler
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_DownSampler_INVALID_ADDRESS
#define nitf_DownSampler_INVALID_ADDRESS 0LL
/*
 * Class:     nitf_DownSampler
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_DownSampler_construct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
