/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_ImageReader */

#ifndef _Included_nitf_ImageReader
#define _Included_nitf_ImageReader
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_ImageReader_INVALID_ADDRESS
#define nitf_ImageReader_INVALID_ADDRESS 0LL
/*
 * Class:     nitf_ImageReader
 * Method:    getInput
 * Signature: ()Lnitf/IOInterface;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageReader_getInput
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageReader
 * Method:    getBlockingInfo
 * Signature: ()Lnitf/BlockingInfo;
 */
JNIEXPORT jobject JNICALL Java_nitf_ImageReader_getBlockingInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_ImageReader
 * Method:    read
 * Signature: (Lnitf/SubWindow;[[B)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_ImageReader_read
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
