/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_IOInterface_Destructor */

#ifndef _Included_nitf_IOInterface_Destructor
#define _Included_nitf_IOInterface_Destructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nitf_IOInterface_Destructor
 * Method:    destructMemory
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_IOInterface_00024Destructor_destructMemory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
