/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_MaxDownSampler */

#ifndef _Included_nitf_MaxDownSampler
#define _Included_nitf_MaxDownSampler
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_MaxDownSampler_INVALID_ADDRESS
#define nitf_MaxDownSampler_INVALID_ADDRESS 0L
/*
 * Class:     nitf_MaxDownSampler
 * Method:    construct
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_nitf_MaxDownSampler_construct
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    apply
 * Signature: ([[B[[BIIIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_MaxDownSampler_apply
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    getRowSkip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_MaxDownSampler_getRowSkip
  (JNIEnv *, jobject);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    getColSkip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_MaxDownSampler_getColSkip
  (JNIEnv *, jobject);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    getMinSupportedBands
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_MaxDownSampler_getMinSupportedBands
  (JNIEnv *, jobject);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    getMaxSupportedBands
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nitf_MaxDownSampler_getMaxSupportedBands
  (JNIEnv *, jobject);

/*
 * Class:     nitf_MaxDownSampler
 * Method:    isMultiBand
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_MaxDownSampler_isMultiBand
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
