/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_Extensions_ExtensionsIterator */

#ifndef _Included_nitf_Extensions_ExtensionsIterator
#define _Included_nitf_Extensions_ExtensionsIterator
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_Extensions_ExtensionsIterator_INVALID_ADDRESS
#define nitf_Extensions_ExtensionsIterator_INVALID_ADDRESS 0L
/*
 * Class:     nitf_Extensions_ExtensionsIterator
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_nitf_Extensions_00024ExtensionsIterator_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Extensions_ExtensionsIterator
 * Method:    next
 * Signature: ()Lnitf/TRE;
 */
JNIEXPORT jobject JNICALL Java_nitf_Extensions_00024ExtensionsIterator_next
  (JNIEnv *, jobject);

/*
 * Class:     nitf_Extensions_ExtensionsIterator
 * Method:    construct
 * Signature: (Lnitf/Extensions;)V
 */
JNIEXPORT void JNICALL Java_nitf_Extensions_00024ExtensionsIterator_construct
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
