/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_IOInterface */

#ifndef _Included_nitf_IOInterface
#define _Included_nitf_IOInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_IOInterface_INVALID_ADDRESS
#define nitf_IOInterface_INVALID_ADDRESS 0LL
#undef nitf_IOInterface_SEEK_CUR
#define nitf_IOInterface_SEEK_CUR 10L
#undef nitf_IOInterface_SEEK_SET
#define nitf_IOInterface_SEEK_SET 20L
#undef nitf_IOInterface_SEEK_END
#define nitf_IOInterface_SEEK_END 30L
#undef nitf_IOInterface_NITF_ACCESS_READONLY
#define nitf_IOInterface_NITF_ACCESS_READONLY 1L
#undef nitf_IOInterface_NITF_ACCESS_WRITEONLY
#define nitf_IOInterface_NITF_ACCESS_WRITEONLY 2L
#undef nitf_IOInterface_NITF_ACCESS_READWRITE
#define nitf_IOInterface_NITF_ACCESS_READWRITE 3L
/*
 * Class:     nitf_IOInterface
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nitf_IOInterface_construct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
