/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nitf_FileHeader */

#ifndef _Included_nitf_FileHeader
#define _Included_nitf_FileHeader
#ifdef __cplusplus
extern "C" {
#endif
#undef nitf_FileHeader_INVALID_ADDRESS
#define nitf_FileHeader_INVALID_ADDRESS 0L
/*
 * Class:     nitf_FileHeader
 * Method:    getBackgroundColor
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getBackgroundColor
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getClassification
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getClassification
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getComplianceLevel
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getComplianceLevel
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getEncrypted
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getEncrypted
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getExtendedHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getExtendedHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getExtendedHeaderOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getExtendedHeaderOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileDateTime
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileDateTime
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileHeader
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileHeader
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileTitle
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileTitle
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getFileVersion
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getFileVersion
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getMessageCopyNum
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getMessageCopyNum
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getMessageNumCopies
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getMessageNumCopies
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumDataExtensions
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumDataExtensions
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumGraphics
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumGraphics
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumImages
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumImages
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumLabels
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumLabels
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumReservedExtensions
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumReservedExtensions
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getNumTexts
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getNumTexts
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getOriginatorName
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getOriginatorName
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getOriginatorPhone
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getOriginatorPhone
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getOriginStationID
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getOriginStationID
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getSecurityGroup
 * Signature: ()Lnitf/FileSecurity;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getSecurityGroup
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getSystemType
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getSystemType
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getUserDefinedHeaderLength
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getUserDefinedHeaderLength
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getUserDefinedOverflow
 * Signature: ()Lnitf/Field;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getUserDefinedOverflow
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getImageInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getImageInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getGraphicInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getGraphicInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getLabelInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getLabelInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getTextInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getTextInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getDataExtensionInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getDataExtensionInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getReservedExtensionInfo
 * Signature: ()[Lnitf/ComponentInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_nitf_FileHeader_getReservedExtensionInfo
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getUserDefinedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getUserDefinedSection
  (JNIEnv *, jobject);

/*
 * Class:     nitf_FileHeader
 * Method:    getExtendedSection
 * Signature: ()Lnitf/Extensions;
 */
JNIEXPORT jobject JNICALL Java_nitf_FileHeader_getExtendedSection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
