from waflib import Options
from os.path import join, exists

BLD_DIRS = 'xml jpeg'

def options(opt):
    opt.recurse(BLD_DIRS)

def configure(conf):
    conf.recurse(BLD_DIRS)

def build(bld):
    bld.recurse(BLD_DIRS)

def distclean(ctx):
    ctx.recurse(BLD_DIRS)
