NAME            = 'nitf'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira1@users.sourceforge.net'
VERSION         = '2.6-dev'
MODULE_DEPS     = 'mt sys'
USELIB          = 'THREAD DL'
USELIB_LOCAL    = 'nitf-c'
TEST_FILTER     = lambda t: t not in 'test_functional.cpp test_handles.cpp test_mem_source.cpp test_static_plugin.cpp'.split()

set_options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
