from os.path import join, exists
from waflib import Options, Utils
from build import CPPBuildContext

MODULES = 'cli except io logging mem mt nitf str sys xml.lite'

def options(opt):
    opt.recurse(MODULES)

def configure(conf):
    conf.env.append_value('INCLUDES_UNITTEST', join(conf.path.abspath(), 'include'))
    conf.recurse(MODULES)

def build(bld):
    bld.recurse(MODULES)

def distclean(context):
    context.recurse(MODULES)
