
import os
from os.path import join, basename
from waflib import Utils

distclean = options = configure = lambda p: None

def build(bld):
    bld.swigModule(name = 'numpyutilstest',
                   use = 'types-python except-python numpyutils-c++',
                   package = 'coda')

