from os.path import join, exists
from waflib import Options, Utils

def options(opt):
    opt.recurse()

def configure(conf):
    if conf.env['COMPILER_CXX'] == 'msvc':
        conf.env.CXXFLAGS += ['/std:c++17']
    else:
        conf.env.CXXFLAGS += ['-std=c++17']
    conf.recurse()

def build(bld):
    variant = bld.env['VARIANT'] or 'default'
    env = bld.all_envs[variant].derive()
    
    bld.recurse()
    if 'DOXYGEN' in env and Options.is_install:
        bld.new_task_gen(rule='${DOXYGEN}', cwd=bld.path.abspath(), always=True)
        try:
            htmlDocs = bld.path.find_dir('doc/html')
            for f in htmlDocs.find_iter():
                relpath = f.relpath_gen(htmlDocs)
                bld.install_files('${PREFIX}/doc/%s' % relpath, f.abspath())
        except:{}


def distclean(context):
    context.recurse()
