def options(opt):
    opt.recurse()

def configure(conf):
    conf.recurse()

def build(bld):
    if bld.env['LIB_TYPE'] == 'shlib':
        bld.recurse('nrt nitf j2k')
    else:
        bld.recurse()

def distclean(context):
    context.recurse()
