MODULES = 'cgm j2k jpeg nitf nrt'

def options(opt):
    opt.recurse(MODULES)

def configure(conf):
    conf.recurse(MODULES)

def build(bld):
    bld.recurse(MODULES)

def distclean(context):
    context.recurse(MODULES)
