import os, sys
from waflib import Options
from waflib.TaskGen import feature, before, task_gen
from build import untarFile

LIBXML_DEFINES = 'USE_LIBXML'

options = build = distclean = lambda x : None

def configure(conf):

    xmlHome = Options.options.xml_home
    xmlLayer = Options.options.xml_layer

    if xmlLayer == 'libxml' :
        conf.env.append_value('DEFINES_XML', LIBXML_DEFINES.split())

        # use an already built version
        if xmlHome:
            # attempt to test the third party library --
            # if test fails then fail the configure
                conf.check(lib='xml2', uselib_store='XML',
                           header_name='libxml/parser.h',
                           function_name='xmlSAXVersion',
                           libpath=os.path.join(xmlHome, 'lib'),
                           includes=os.path.join(xmlHome, 'include'),
                           msg='Checking for library libxml', okmsg=xmlHome,
                           mandatory=True)

        # we don't currently support building within waf,
        # so use an already built version that's on the system
        else:
                conf.check(lib='xml2', uselib_store='XML',
                           header_name='libxml/parser.h',
                           function_name='xmlSAXVersion',
                           msg='Checking for library libxml',
                           mandatory=True)
