NAME            = 'scene'
MAINTAINER      = 'asylvest@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'io math.linear math.poly types'
TEST_FILTER     = 'test_scene.cpp'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
    
