import os

configure = distclean = options = lambda p: None

def build(bld):
    bld(feautres='py',
        name='py_test_utils',
        source = bld.path.make_node('source').ant_glob('**/*.py'),
        install_path=os.path.join(
            bld.env['install_pydir'], 'test_utils'))
