NAME            = 'tiff'
VERSION         = '1.0'
MODULE_DEPS     = 'libtiff mt io'
USELIB_LOCAL    = 'libtiff-c'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
