import os
import Options

def set_options(opt):
    opt.tool_options('python')
    opt.add_option('--disable-python', action='store_false', dest='python',
                   help='Disable python', default=True)
    
def configure(conf):
    if Options.options.python:
        conf.check_tool('python')
        conf.check_python_version((2,4,2))
        conf.check_python_headers()

def build(bld):
    variant = bld.env['VARIANT'] or 'default'
    env = bld.env_of_name(variant)
    if 'PYTHON' in env:
        bld.add_subdirs('nitf')

def distclean(context):
    pass
