NAME            = 'cphd'
MAINTAINER      = 'clyde.stanfield@mdaus.com'
VERSION         = '2.1.2'
MODULE_DEPS     = 'six.sicd'
TEST_DEPS       = 'cli'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
