import Options

NAME            = 'cgm'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira_1@users.sourceforge.net'
VERSION         = '2.7-dev'
MODULE_DEPS     = 'nitf nrt'
LANG            = 'c'
USELIB_LOCAL    = 'nitf-c nrt-c'
DEFINES         = 'NITF_MODULE_EXPORTS'


set_options = configure = distclean = lambda p: None

def build(bld):
    env = bld.module(**globals())

    #run doxygen
    if 'DOXYGEN' in env and Options.is_install:
        bld.new_task_gen(rule='${DOXYGEN}', cwd=bld.path.abspath(), always=True)
        try:
            htmlDocs = bld.path.find_dir('doc/html')
            for f in htmlDocs.find_iter():
                relpath = f.relpath_gen(htmlDocs)
                bld.install_files('${PREFIX}/share/doc/nitf-cgm/c/%s' % relpath, f.abspath())
        except:{}

