import os
import Options

def build(bld):
    variant = bld.env['VARIANT']
    env = bld.env_of_name(variant)
    env.set_variant(variant)
    
    includes = ['include']
    libname = 'cgm'
    
    objs = bld.new_task_gen('cc', includes=includes,
            target='CGM_objs', export_incdirs=includes,
            env=env.copy(), uselib_local='NITRO_objs',
            defines = 'NITF_MODULE_EXPORTS')
    objs.find_sources_in_dirs('source')
    
    lib = bld.new_task_gen('cc', 'staticlib', includes=includes,
                           target='%s-c' % libname, uselib_local='NITRO',
                           export_incdirs=includes, env=env.copy(),
                           add_objects='CGM_objs', name='CGM')
    
    #build tests
    testDir = bld.path.find_dir('tests')
    for test in testDir.find_iter(in_pat=['test*.c'],
                                  maxdepth=1, flat=True).split(' '):
        exe = bld.new_task_gen('cc', 'program', source=test,
                               uselib_local='CGM',
                               target=os.path.splitext(test)[0],
                               path=testDir,
                               install_path='${PREFIX}/share/nitf-cgm/tests')
    
    #install headers
    for f in bld.path.find_dir('include').find_iter():
        relpath = f.relpath_gen(bld.path)
        bld.install_files('${PREFIX}/%s' % os.path.dirname(relpath), relpath)
    
    #run doxygen
    if 'DOXYGEN' in env and Options.is_install:
        bld.new_task_gen(rule='${DOXYGEN}', cwd=bld.path.abspath(), always=True)
        try:
            htmlDocs = bld.path.find_dir('doc/html')
            for f in htmlDocs.find_iter():
                relpath = f.relpath_gen(htmlDocs)
                bld.install_files('${PREFIX}/share/doc/nitf-cgm/c/%s' % relpath, f.abspath())
        except:{}

