NAME            = 'six.sidd'
MAINTAINER      = 'adam.sylvester@mdaus.com'
MODULE_DEPS     = 'scene tiff nitf xml.lite six mem'
TEST_DEPS       = 'cli'

options = configure = distclean = lambda p: None

def build(bld):
    modArgs = globals()
    modArgs['VERSION'] = bld.env['SIX_VERSION']
    bld.module(**modArgs)

    # install the schemas
    lib = bld.get_tgen_by_name('six.sidd-c++')
    lib.targets_to_add.append(bld(features='install_tgt', pattern='**/*',
                                  dir=bld.path.make_node('conf/schema'),
                                  install_path='${PREFIX}/conf/schema/six/'))
