import os
from waflib import Options

NAME            = 'nrt'
MAINTAINER      = 'tzellman@users.sourceforge.net gojira_1@users.sourceforge.net'
VERSION         = '2.7'
MODULE_DEPS     = ''
LANG            = 'c'
USELIB          = 'THREAD DL RT MATH'
DEFINES         = 'NRT_MODULE_EXPORTS'


configure = options = distclean = lambda p: None

def build(bld):
    env = bld.module(**globals())
    
        
    #run doxygen
    if 'DOXYGEN' in env and Options.is_install:
        bld(rule='${DOXYGEN}', cwd=bld.path.abspath(), always=True)
        try:
            htmlDocs = bld.path.find_dir('doc/html')
            for f in htmlDocs.find_iter():
                relpath = f.path_from(htmlDocs)
                bld.install_files('${PREFIX}/share/doc/nitf/c/%s' % relpath, f.abspath())
        except:{}
