NAME            = 'six.sicd'
MAINTAINER      = 'adam.sylvester@gd-ais.com'
VERSION         = '2.1.1'
MODULE_DEPS     = 'scene nitf xml.lite six mem'
UNITTEST_DEPS   = 'cli sio.lite'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())

    # install the schemas
    lib = bld.get_tgen_by_name('six.sicd-c++')
    lib.targets_to_add.append(bld(features='install_tgt', pattern='**/*',
                                  dir=bld.path.make_node('conf/schema'),
                                  install_path='${PREFIX}/conf/schema/six/'))
