import os
from waflib import Options
from javatool import java_module

NAME            = 'cgm'
MAINTAINER      = 'asylvest@users.sourceforge.net'
VERSION         = '2.7'
MODULE_DEPS     = 'nitf'
CLASSPATH       = ''
COMPAT          = '1.5'
USE             = 'cgm-c'

configure = options = distclean = lambda x: None

def build(bld):
    java_module(bld, **globals())				

    tests = bld.path.ant_glob(os.path.join('src', 'test', 'cgm', '*.java'))
    test_targets = []
    for test in tests:
        test_targets.append(os.path.splitext(str(test))[0])
    
    bld(features='add_targets', target='cgm-java-tests',
        targets_to_add=test_targets)
