distclean = options = lambda p: None

def configure(conf):
    conf.env['prefix_logging'] = 'coda_'

def build(bld):
    bld.swigModule(name = 'logging', use = 'logging-c++ config-python', package='coda')
