NAME            = 'six'
MODULE_DEPS     = 'scene nitf xml.lite logging math.poly numpyutils mem sys str units except types config gsl std'
USE             = 'XML_DATA_CONTENT-static-c'

options = configure = distclean = lambda p: None

def build(bld):
    modArgs = globals()
    modArgs['VERSION'] = bld.env['SIX_VERSION']
    bld.module(**modArgs)
