NAME            = 'six'
MAINTAINER      = 'adam.sylvester@mdaus.com'
MODULE_DEPS     = 'scene nitf xml.lite logging math.poly mem'
TARGETS_TO_ADD  = 'XML_DATA_CONTENT'

options = configure = distclean = lambda p: None

def build(bld):
    modArgs = globals()
    modArgs['VERSION'] = bld.env['VERSION']
    bld.module(**modArgs)
