from waflib import Options
from javatool import java_module

NAME            = 'nitf'
MAINTAINER      = 'asylvest@users.sourceforge.net'
VERSION         = '2.7'
MODULE_DEPS     = ''
CLASSPATH       = 'commons-io-1.3.2.jar commons-cli-1.0-beta-2.jar commons-lang-2.0.jar commons-logging-1.1.1.jar log4j-1.2.13.jar'
COMPAT          = '1.5'
USE             = 'nitf-c'

options = distclean = lambda x: None

def configure(conf):
    Options.options.force_jni = True

def build(bld):
    java_module(bld, **globals())				
