NAME            = 'io'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '1.0'
MODULE_DEPS     = 'sys mem'
SOURCE_FILTER   = 'MMapInputStream.cpp'
TEST_FILTER     = 'mmByteStreamTest.cpp'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
