NAME            = 'six.convert'
MAINTAINER      = 'jonathan.means@mdaus.com'
MODULE_DEPS     = 'io plugin six.sicd sys xml.lite'

options = configure = distclean = lambda p: None


def build(bld):
    modArgs = globals()
    modArgs['VERSION'] = bld.env['SIX_VERSION']
    bld.module(**modArgs)

