import os
import Options


def build(bld):
    includes = ['include']
    libname = 'nitf'
    
    lib = bld.new_task_gen('cc', 'staticlib', includes=includes,
                           target='%s-c' % libname,
                           export_incdirs=includes,
                           uselib = 'THREAD DL NITRO'.split(),
                           name='NITRO')
    lib.find_sources_in_dirs('./source', excludes=[])
    lib.cloneVariants()
    
    pluginNode = bld.path.find_dir('shared')
    libPattern = bld.env['shlib_PATTERN']
    if libPattern.startswith('lib'):
        libPattern = libPattern[3:]
    for p in pluginNode.find_iter(in_pat=['*.c'], maxdepth=1, flat=True).split(' '):
        plugin = bld.new_task_gen('cc', 'shlib', source=p,
                                  uselib_local='NITRO',
                                  target=os.path.splitext(p)[0],
                                  path=pluginNode,
                                  install_path='${PREFIX}/share/nitf/plugins')
        for t in plugin.cloneVariants():
            t.env['shlib_PATTERN'] = libPattern
        
    
    #build tests
    testDir = bld.path.find_dir('tests')
    tests = testDir.find_iter(in_pat=['test*.c'],
                              ex_pat=['test_1band_rw_line.c', 'test_fileIO.c',
                                      'test_hash_table_2.c', 'test_writer_s.c',
                                      'test_des_read.c', 'test_read_acftb.c',
                                      'test_add_masks.c', 'test_plugin_reg_1.c',
                                      'test_des_write.c', 'test_ImageIO_support.c',
                                      'test_make_pattern.c', 'test_des.c',
                                      'test_ext_iter.c', 'test_ImageIO_read_data.c',
                                      'test_ImageIO_writePattern.c'],
                              maxdepth=1, flat=True).split(' ')
    for test in tests:
        exe = bld.new_task_gen('cc', 'program', source=test,
                               uselib_local='NITRO',
                               target=os.path.splitext(test)[0],
                               path=testDir,
                               install_path='${PREFIX}/share/nitf/tests')
        exe.cloneVariants()
    
    #install headers
    for f in bld.path.find_dir('include').find_iter():
        relpath = f.relpath_gen(bld.path)
        bld.install_files('${PREFIX}/%s' % os.path.dirname(relpath), relpath)
        
    #run doxygen
    if 'DOXYGEN' in bld.env and Options.is_install:
        bld.new_task_gen(rule='${DOXYGEN}', cwd=bld.path.abspath(), always=True)
        try:
            htmlDocs = bld.path.find_dir('doc/html')
            for f in htmlDocs.find_iter():
                relpath = f.relpath_gen(htmlDocs)
                bld.install_files('${PREFIX}/share/doc/nitf/c/%s' % relpath, f.abspath())
        except:{}
