NAME            = 'coda_oss'
VERSION         = '1.0'
MODULE_DEPS     = 'config gsl'
USELIB          = 'THREAD DL RT SOCKET'
UNITTEST_DEPS   = ''

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
